### ISSUE TITLE
Wrong hash signatures for SLF4J dependencies

### ISSUE THREAD

**Issue by mcdonnell-john** [lkishalmi/incubator-netbeans#7]
Wrong hash signatures for SLF4J dependencies

**Steps to Reproduce**
1. Clean the local maven repository of the slf4j
2. Perform a maven dependency get: `mvn dependency:get -Dartifact=org.slf4j:slf4j-api:1.7.25`
2. Build the branch

**Expected Result**
Build completes successfully

**Actual Result**
Build fails as the hash's persisted in the branch do not match the hash's computed against the fresh slf4j files.

I locally had to use:
`
DA76CA59F6A57EE3102F8F9BD9CEE742973EFA8A org.slf4j:slf4j-api:1.7.25
BCCDA40EBC8067491B32A88F49615A747D20082D org.slf4j:slf4j-jdk14:1.7.25
`

**Impact**
Without fixing this issue a PR to Apache NetBeans will fail as Jenkins/Travis will compute the wrong hashes

**Comment by lkishalmi** [comment]
Hashes fixed. I can't remember from where I took those initially.
